version: '3.8'

services:
  polybot:
    build: .
    container_name: polybot
    restart: unless-stopped
    ports:
      - "192.168.1.75:8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs